name: Deploy to GitHub Pages

permissions:
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Set REACT_APP_GITHUB_REPOSITORY
        run: echo "REACT_APP_GITHUB_REPOSITORY=$GITHUB_REPOSITORY" >> $GITHUB_ENV

      - name: Build the site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
